In [14]:
# Keep only 'Property Type' and 'Property Subtype' columns in ubc_df
ubc_df = ubc_df[['Property Type', 'Property Subtype','Property Id','State']]
ubc_df

       Property Type        Property Subtype  Property Id State
0             Office                     NaN       824312    VA
1             Office     Hospitality Related       824285    VA
2             Office                     NaN        18310    VA
3               Land                     NaN      1954254    CO
4                NaN        Mobile Home Park      1154012    OR
...              ...                     ...          ...   ...
563648        Office             Vacant Land      3608517    TX
563649        Office                     NaN      3608526    CO
563650        Office      Medical/Healthcare      3608445    ID
563651        Office                     NaN      3608520    MI
563652        Office  Warehouse/Distribution      3608525    NC

[563653 rows x 4 columns]

In [16]:
# Load and concatenate city sheets from multiple DOE files
file_paths = [
    r"C:\Users\clint\Desktop\data\data\DOE\2019 Commercial Building Inventory - Northeast.xlsb",
    r"C:\Users\clint\Desktop\data\data\DOE\2019 Commercial Building Inventory - South Atlantic.xlsb",
    r"C:\Users\clint\Desktop\data\data\DOE\2019 Commercial Building Inventory - South Central.xlsb",
    r"C:\Users\clint\Desktop\data\data\DOE\2019 Commercial Building Inventory - West.xlsb",
    r"C:\Users\clint\Desktop\data\data\DOE\2019 Commercial Building Inventory - Midwest.xlsb"
]

# Load city sheets and concatenate them into a single DataFrame
city_dfs = [pd.read_excel(file_path, sheet_name='City', engine='pyxlsb') for file_path in file_paths]
combined_city_df = pd.concat(city_dfs, ignore_index=True)

# Rename unnamed columns
combined_city_df.columns = [col if not col.startswith('Unnamed') else f'Unnamed_{i}' for i, col in enumerate(combined_city_df.columns)]
combined_city_df

,Unnamed_0,city_name,Unnamed_2,countyname,statefp,statecode,bldg_count,reported_propertytype,reported_propertysubtype,rentablebuildingarea_mean,...,cbecs,Unnamed_15,area_sum,Unnamed_17,placeid,countyid,Unnamed_20,Unnamed_21,Unnamed_22,Unnamed_23
0,NaN,Andover,NaN,Tolland County,9,CT,1,Flex,Light Manufacturing,3900,...,Other,NaN,3900,NaN,901080.0,9013,NaN,NaN,NaN,NaN
1,NaN,Andover,NaN,Tolland County,9,CT,1,Industrial,Warehouse,4600,...,Non-refrigerated warehouse,NaN,4600,NaN,901080.0,9013,NaN,NaN,NaN,NaN
2,NaN,Andover,NaN,Tolland County,9,CT,1,Industrial,NaN,5000,...,Other,NaN,5000,NaN,901080.0,9013,NaN,NaN,NaN,NaN
3,NaN,Andover,NaN,Tolland County,9,CT,1,Multi-Family,Apartments,25000,...,Apartments,NaN,25000,NaN,901080.0,9013,NaN,NaN,NaN,NaN
4,NaN,Andover,NaN,Tolland County,9,CT,1,Multi-Family,Apartments,30000,...,Apartments,NaN,30000,NaN,901080.0,9013,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2246480,NaN,Wrightstown,NaN,Brown County,55,WI,1,Retail,Storefront Retail/Office,4600,...,Mixed-use office,NaN,4600,NaN,5589150.0,55009,NaN,NaN,NaN,NaN
2246481,NaN,Wrightstown,NaN,Brown County,55,WI,1,Retail,Storefront Retail/Office,9400,...,Mixed-use office,NaN,9400,NaN,5589150.0,55009,NaN,NaN,NaN,NaN
2246482,NaN,Wrightstown,NaN,Brown County,55,WI,1,Retail,NaN,2500,...,Retail store,NaN,2500,NaN,5589150.0,55009,NaN,NaN,NaN,NaN
2246483,NaN,Wrightstown,NaN,Outagamie County,55,WI,1,Retail,NaN,1800,...,Retail store,NaN,1800,NaN,5589150.0,55087,NaN,NaN,NaN,NaN
2246484,NaN,Wrightstown,NaN,Brown County,55,WI,1,Specialty,Post Office,6000,...,Post office/postal center,NaN,6000,NaN,5589150.0,55009,NaN,NaN,NaN,NaN

In [17]:
# Keep only 'statecode', 'reported_propertytype', and 'reported_propertytype' columns in combined_city_df
combined_city_df = combined_city_df[['statecode', 'reported_propertytype', 'reported_propertytype']]
combined_city_df

        statecode reported_propertytype reported_propertytype
0              CT                  Flex                  Flex
1              CT            Industrial            Industrial
2              CT            Industrial            Industrial
3              CT          Multi-Family          Multi-Family
4              CT          Multi-Family          Multi-Family
...           ...                   ...                   ...
2246480        WI                Retail                Retail
2246481        WI                Retail                Retail
2246482        WI                Retail                Retail
2246483        WI                Retail                Retail
2246484        WI             Specialty             Specialty

[2246485 rows x 3 columns]

In [20]:
# Load the 'university-of-british-columbia-leases-2025-04-02.csv' and 'university-of-british-columbia-sales-2025-04-02.csv' files
lease_file_path = r'C:\Users\clint\Desktop\data\data\university-of-british-columbia-leases-2025-04-02.csv'
sales_file_path = r'C:\Users\clint\Desktop\data\data\university-of-british-columbia-sales-2025-04-02.csv'

lease_df = pd.read_csv(lease_file_path)
sales_df = pd.read_csv(sales_file_path)

# Isolate specific columns
lease_df = lease_df[['Property Type', 'Property Subtype', 'Property Id', 'State']]
sales_df = sales_df[['Property Type', 'Property Subtype', 'Property Id', 'State']]

# Combine the dataframes with sales_df above lease_df
combined_df = pd.concat([sales_df, lease_df], ignore_index=True)

C:\Users\clint\AppData\Local\Temp\ipykernel_19584\762166346.py:5: DtypeWarning: Columns (15,35,37,59,61,67,71,73,76,77,78,80,82,85) have mixed types. Specify dtype option on import or set low_memory=False.
  lease_df = pd.read_csv(lease_file_path)
C:\Users\clint\AppData\Local\Temp\ipykernel_19584\762166346.py:6: DtypeWarning: Columns (8,52,73,77) have mixed types. Specify dtype option on import or set low_memory=False.
  sales_df = pd.read_csv(sales_file_path)
C:\Users\clint\AppData\Local\Temp\ipykernel_19584\762166346.py:6: DtypeWarning: Columns (8,52,73,77) have mixed types. Specify dtype option on import or set low_memory=False.
  sales_df = pd.read_csv(sales_file_path)

        Property Type        Property Subtype  Property Id State
2              Office                     NaN        18310    VA
5              Office                     NaN       136712    CO
6        Multi-Family             Vacant Land       952565    NJ
7          Industrial  Warehouse/Distribution       499266    NJ
10       Multi-Family              Apartments      1884375    TN
...               ...                     ...          ...   ...
1732643        Office      Medical/Healthcare        18544    VA
1732644        Office                     NaN         1069    NY
1732645    Industrial  Warehouse/Distribution       123156    CA
1732646    Industrial  Warehouse/Distribution        15156    CA
1732649    Industrial                Flex/R&D      3131383    IL

[1178917 rows x 4 columns]

In [21]:
# Remove repeated Property Ids, keeping only the highest index row
combined_df = combined_df.loc[combined_df.groupby('Property Id').apply(lambda x: x.index.max())]
combined_df.reset_index(drop=True, inplace=True)
combined_df

C:\Users\clint\AppData\Local\Temp\ipykernel_19584\553175234.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  combined_df = combined_df.loc[combined_df.groupby('Property Id').apply(lambda x: x.index.max())]

       Property Type Property Subtype  Property Id State
0             Retail          Parking            1    NY
1             Retail       Apartments            2    NY
2             Office              NaN            3    NY
3             Retail              NaN            4    NY
4             Office        Mixed-Use            5    NY
...              ...              ...          ...   ...
759618           NaN              NaN      3611385    NY
759619    Industrial         Flex/R&D      3611389    FL
759620    Industrial         Flex/R&D      3611390    FL
759621           NaN              NaN      3611391    CA
759622           NaN              NaN      3611399    NY

[759623 rows x 4 columns]

In [ ]:
# Save combined_city_df as a CSV file in the Data directory
combined_city_df.to_csv(r'C:\Users\clint\Desktop\compstak-ra\Data\combined_city_df.csv', index=False)

In [ ]:
# Save combined_df as a CSV file in the Data directory
combined_df.to_csv(r'C:\Users\clint\Desktop\compstak-ra\Data\combined_df.csv', index=False)